// Mocks generated by Mockito 5.4.4 from annotations
// in movie_zone/test/movie_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_zone/core/entities/app_error.dart' as _i6;
import 'package:movie_zone/core/entities/no_params.dart' as _i8;
import 'package:movie_zone/features/main/domain/entities/movie_results_entity.dart'
    as _i7;
import 'package:movie_zone/features/main/domain/repository/main_repository.dart'
    as _i2;
import 'package:movie_zone/features/main/domain/usecases/movie_usecases.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMainRepository_0 extends _i1.SmartFake
    implements _i2.MainRepository {
  _FakeMainRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMoviesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoviesUsecase extends _i1.Mock implements _i4.GetMoviesUsecase {
  MockGetMoviesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MainRepository get mainRepository => (super.noSuchMethod(
        Invocation.getter(#mainRepository),
        returnValue: _FakeMainRepository_0(
          this,
          Invocation.getter(#mainRepository),
        ),
      ) as _i2.MainRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppError, _i7.MovieResultsEntity>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.AppError, _i7.MovieResultsEntity>>.value(
                _FakeEither_1<_i6.AppError, _i7.MovieResultsEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AppError, _i7.MovieResultsEntity>>);
}
