// Mocks generated by Mockito 5.4.4 from annotations
// in movie_zone/test/movie_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_zone/core/entities/app_error.dart' as _i5;
import 'package:movie_zone/features/auth/domain/entities/user_entity.dart'
    as _i8;
import 'package:movie_zone/features/main/domain/entities/genre_results_entity.dart'
    as _i9;
import 'package:movie_zone/features/main/domain/entities/movie_detail_entity.dart'
    as _i7;
import 'package:movie_zone/features/main/domain/entities/movie_results_entity.dart'
    as _i6;
import 'package:movie_zone/features/main/domain/entities/tv_results_entity.dart'
    as _i10;
import 'package:movie_zone/features/main/domain/repository/main_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MainRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainRepository extends _i1.Mock implements _i3.MainRepository {
  MockMainRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.MovieResultsEntity>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>> getMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.MovieResultsEntity>(
          this,
          Invocation.method(
            #getMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i7.MovieDetailEntity>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i7.MovieDetailEntity>>.value(
                _FakeEither_0<_i5.AppError, _i7.MovieDetailEntity>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i7.MovieDetailEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>
      getSuggestedMovies(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getSuggestedMovies,
              [id],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.MovieResultsEntity>(
              this,
              Invocation.method(
                #getSuggestedMovies,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>
      getPopularMovies() => (super.noSuchMethod(
            Invocation.method(
              #getPopularMovies,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i6.MovieResultsEntity>(
              this,
              Invocation.method(
                #getPopularMovies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppError, _i6.MovieResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i8.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppError, _i8.UserEntity>>.value(
            _FakeEither_0<_i5.AppError, _i8.UserEntity>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i8.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i9.GenreResultsEntity>> getGenres() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGenres,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i9.GenreResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i9.GenreResultsEntity>(
          this,
          Invocation.method(
            #getGenres,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i9.GenreResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, _i10.TvResultsEntity>> getTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTv,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AppError, _i10.TvResultsEntity>>.value(
                _FakeEither_0<_i5.AppError, _i10.TvResultsEntity>(
          this,
          Invocation.method(
            #getTv,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, _i10.TvResultsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppError, void>> editCurrentUser(
          _i8.UserEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #editCurrentUser,
          [user],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppError, void>>.value(
            _FakeEither_0<_i5.AppError, void>(
          this,
          Invocation.method(
            #editCurrentUser,
            [user],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppError, void>>);
}
